force-app/main/default/objects/Application__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lower</fullName>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Critical</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WSLog__c/WSLog__c.object-meta.xml
<CustomObject>
    <description>Contain errors that occured during webservices call</description>
    <label>WSLog</label>
    <nameField>
        <displayFormat>WSL-{0000}</displayFormat>
        <label>WSLog Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WSLogs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/WSLog__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>WSLogs</relationshipLabel>
    <relationshipName>WSLogs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/WSLog__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <defaultValue>&apos;Lower&apos;</defaultValue>
    <label>Priority</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lower</fullName>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Critical</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WSLog__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <description>Name of the service involved</description>
    <label>Service</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WSLog__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inbound</fullName>
            </value>
            <value>
                <fullName>Outbound</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/WSLogController.cls
public with sharing class WSLogController {
    

@AuraEnabled(cacheable=true)
public static List<WSLog__c> getWSLogs(List<String> typeFilter, 
                                       List<String> serviceFilter, 
                                       List<String> applicationFilter, 
                                       List<String> priorityFilter) {
    String query = 'SELECT Id, Name, Type__c, Service__c, Application__c, Priority__c, Message__c FROM WSLog__c WHERE Id != null';
    if (typeFilter != null && !typeFilter.isEmpty()) {
        query += ' AND Type__c IN :typeFilter';
    }
    if (serviceFilter != null && !serviceFilter.isEmpty()) {
        query += ' AND Service__c IN :serviceFilter';
    }
    if (applicationFilter != null && !applicationFilter.isEmpty()) {
        query += ' AND Application__c IN :applicationFilter';
    }
    if (priorityFilter != null && !priorityFilter.isEmpty()) {
        query += ' AND Priority__c IN :priorityFilter';
    }
    
    // Exécution de la requête
    return Database.query(query);
}
@AuraEnabled(cacheable=true)
public static List<WSLog__c> getWSLogsByApplicationId(Id applicationId) {
    return getWSLogs(
        null, 
        null, 
        new List<String>{applicationId}, 
        null
    );
}



}